=== Tinhh/XML_APTECH/ss2/cart.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="cart">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="date" type="xsd:string" />
                <xsd:element name="grand_total" type="xsd:integer" />

                <xsd:element name="customer">
                    <xsd:complexType>
                        <xsd:sequence>

                        <xsd:element name="c_name" type="xsd:string" />

                        <xsd:element name="c_tel">
                            <xsd:simpleType>
                                <xsd:restriction base="xsd:integer">
                                    <xsd:minLength value="10" />
                                    <xsd:maxLength value="11" />
                                </xsd:restriction>
                            </xsd:simpleType>
                        </xsd:element>

                        <xsd:element name="c_address">
                            <xsd:simpleType>
                                <xsd:restriction base="xsd:string">
                                    <xsd:minLength value="5" />
                                    <xsd:maxLength value="200" />
                                </xsd:restriction>
                            </xsd:simpleType>
                        </xsd:element>

                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>

                <xsd:element name="item">
                    <xsd:complexType>
                        <xsd:sequence>

                            <xsd:element name="product"  maxOccurs="10">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="p_name">
                                            <xsd:simpleType>
                                                <xsd:restriction base="xsd:string">
                                                    <xsd:minLength value="5" />
                                                    <xsd:maxLength value="200" />
                                                </xsd:restriction>
                                            </xsd:simpleType>
                                        </xsd:element>

                                        <xsd:element name="qty">
                                            <xsd:simpleType>
                                                <xsd:restriction base="xsd:integer">
                                                    <xsd:minInclusive value="1" />
                                                    <xsd:maxInclusive value="10" />
                                                </xsd:restriction>
                                            </xsd:simpleType>
                                        </xsd:element>

                                        <xsd:element name="price">
                                            <xsd:simpleType>
                                                <xsd:restriction base="xsd:integer">
                                                    <xsd:minLength value="5" />
                                                </xsd:restriction>
                                            </xsd:simpleType>
                                        </xsd:element>

                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>

                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>


            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== Tinhh/XML_APTECH/ss2/cart.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE cart SYSTEM "demo.dtd">
<cart xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cart.xsd">

    <date>22/2/2022</date>
    <grand_total>20000000</grand_total>
    <customer>
        <c_name>Bui Van Tinh</c_name>
        <c_tel>0972030182</c_tel>
        <c_address>8 ton that thuyet</c_address>
    </customer>
    <item>
        <product>
            <p_name>TV SONY 59inch</p_name>
            <qty>1</qty>
            <price>20000000</price>
        </product>

        <product>
            <p_name>TV SONY 59inch</p_name>
            <qty>1</qty>
            <price>20000000</price>
        </product>

    </item>
</cart>
