=== Tinhh/XML_APTECH/ss2/demo.dtd
<!ELEMENT note (to+,from,heading,body)>
        <!ELEMENT to (#PCDATA)>
        <!ELEMENT from (#PCDATA)>
        <!ELEMENT heading (#PCDATA)>
        <!ELEMENT body (title,(content|desc))>
        <!ELEMENT title (#PCDATA)>
        <!ELEMENT content (#PCDATA)>
        <!ELEMENT desc (#PCDATA)>
<!ELEMENT cart (date,grand_total,customer,item)>
        <!ELEMENT date (#PCDATA)>
        <!ELEMENT grand_total (#PCDATA)>
        <!ELEMENT customer (c_name,c_tel,c_address)>
        <!ELEMENT c_name (#PCDATA)>
        <!ELEMENT c_tel (#PCDATA)>
        <!ELEMENT c_address (#PCDATA)>
        <!ELEMENT item (product+)>
        <!ELEMENT product (p_name,qty,price)>
        <!ELEMENT p_name (#PCDATA)>
        <!ELEMENT qty (#PCDATA)>
        <!ELEMENT price (#PCDATA)>

=== Tinhh/XML_APTECH/ss2/DTD.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE note SYSTEM "demo.dtd">
<note>
    <to>HaLong</to>
    <to>CatBa</to>
    <to>CoThanh</to>
    <from>Hanoi</from>
    <heading>CHuyen phat nhanh</heading>
    <body>
        <title>Hang de vo, can than</title>
        <content>Chuyen phat chu y hang hoa</content>
    </body>
</note>

=== Tinhh/XML_APTECH/ss3/cart_ss3.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/css" href="cart_ss3.css" ?>
<!DOCTYPE cart SYSTEM "demo.dtd">
<cart id="cart" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cart_ss3.xsd">

    <date id="date">22/2/2022</date>
    <grand_total id="grand">20000000</grand_total>
    <customer id="cus">
        <c_name id="a">Bui Van Tinh</c_name>
        <c_tel id="a">0972030182</c_tel>
        <c_address id="a">8 ton that thuyet</c_address>
    </customer>
    <item id="item">
        <product id="pro">
            <p_name>TV SONY 59inch</p_name>
            <qty>1</qty>
            <price>20000000</price>
        </product>

        <product id="pro">
            <p_name>TV SONY 59inch</p_name>
            <qty>1</qty>
            <price>20000000</price>
        </product>

    </item>
</cart>
